### ISSUE TITLE
Broken Topology Modeler

### ISSUE THREAD

**Issue by wagnerdk** [eclipse/winery#185]
**Current Behavior:**
While opening the Topology Modeler the error  "Error: Unable to compile class for JSP: An error occurred at line: [64] in the jsp file: [/WEB-INF/tags/common/templates/properties.tag] Type mismatch: cannot convert from Map to Properties 61: // We never read props if in paletteMode 62: props = null; 63: } else { 64: props = ModelUtilities.getPropertiesKV(template); 65: } 66: %> 67: <%-- stores wrapper element name and namespace to ease serialization--%> Stacktrace:" appears.

**Expected Behavior:**
The Topology Modeler should open.

**Steps to Reproduce:**

  1. Use an empty repository (I tried it with populated repositories as well) 
  2. Open Winery in Chrome
  3. Add a Service Template
  4. Open the Service Template
  4. Select the tab "Topology Template"
  5. Click on "Open Editor"

![winerytopologymodelerbroken](https://user-images.githubusercontent.com/18245675/31837059-aa0d4208-b5d7-11e7-9165-3e675448e086.gif)

**System Information:**
Chrome 61.0.3163.100 64 Bit
Windows 10 64 Bit
Winery Installation via https://github.com/OpenTOSCA/opentosca-docker latest version

**Comment by koppor** [comment]
Can you please try latest docker snapshot? For issues of OpenTOSCA Winery, we recommend using filing an issue at https://github.com/opentosca/winery/issues.
