### ISSUE TITLE
default values are not shown in tables

### ISSUE THREAD

**Issue by F7502** [eclipse/winery#4]
There are several tables that contain the two columns "lower bound" and "upper bound" (e.g. the tables for the requirements and capabilities of node types). When I add an entry to this table, the new entry is immediately added to the table and all values that I specified are shown. However, when I leave that page and come back later, the values for "lower bound" and "upper bound" are in most cases not shown anymore. I first thought there is a bug, but then I realized that this is done intentionally. When values are set to the default values (in case of "lower bound" and "upper bound" this is "1"), these are not shown!

As an example, in `reqandcapdefs.tag` the values for "lower bound" and "upper bound" are added to the table as follows:

`<td>${w:renderMinInstances(r.def.lowerBound)}</td>`

The function `renderMinInstances()` contains the logic to replace default values with an emtpy string so that they are not shown. I suggest to change this to:

`<td>${r.def.lowerBound}</td>`

I think that it is far more user friendly to always show these values. Nobody knows all the default values from memory! In addition, the behavior is anyway inconsistent, as the values are nevertheless shown, when entries are initially added to a table.

**Comment by koppor** [comment]
Refs `org.eclipse.winery.model.tosca.TNodeTemplate#getMaxInstances`.

- In case the value is `null`, the default value should be shown in another color.
- In case the user sets a value explicitly, this value should in the same way as other explicit values.
- It has to be possible to remove an explicit value
