### ISSUE TITLE
Can't add requirement definitions

### ISSUE THREAD

**Issue by youcefouarab** [eclipse/winery#667]
The following message appears
Http failure response for http://localhost:8080/winery/nodetypes/example/HostNode/requirementdefinitions: 500 OK

**Comment by lharzenetter** [comment]
Which version do you use and which repository type, i.e., YAML or XML?

**Comment by youcefouarab** [comment]
according to "about" the version is Winery 1.0.0-SNAPSHOT
repository type is YAML

i do have the latest main branch

**Comment by lharzenetter** [comment]
Okay, I still cannot reproduce it. Can you attach the error log?

**Comment by youcefouarab** [comment]
i re-setup everything and that seems to have fixed it.
thanks anyway :)
